name: Build and Deploy

on:
  push:
    branches: [master]

jobs:
  build-deploy-gh-pages:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build and Deploy app to GitHub Pages
        uses: lucetre/build-deploy-gh-pages@v0.3
        with:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
